# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'd2:e7:e1:3c:9d:20:2d:1f:63:f3:14:9e:d8:84:2a:18'
      - run:
          name: Deploy Over SSH
          command: |
            echo 'deploying master branch'
            ssh -v $DROPLET_USER@$DROPLET_IP "cd ~/Websites/cs490-backend; git fetch; git reset --hard origin/master; pm2 restart 1"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
